model_family: googlenet
sample_count: 2000
checkpoint_dir: ./data
submodule_level: 2
n_classes: 1000
input_shape: [3, 224, 224]
sample_space:
    channel:
       start: 0.2
       end: 1.8
       step: 0.1
    kernelsize: [1, 3, 5, 7]
    es:
       start: 0.8
       end: 1.8
       step: 0.1
